# Generated by Django 4.0 on 2024-01-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='viloyat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.viloyatlar'),
        ),
    ]
