# Generated by Django 4.0 on 2024-01-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_user_role_delete_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_count',
            field=models.IntegerField(default=0),
        ),
    ]
