version: '3.9'
services:
  django_app:
    build: .
    env_file:
      - .env
    volumes:
      - static_vol:/app/staticfiles
      - media_vol:/app/media
    ports:
      - "8000:8000"
    
    


  channels_app:
    build: .
    env_file:
      - .env
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    ports:
      - "8001:8001"


  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/staticfiles
      - media_vol:/app/media
    ports:
      - "80:80"
    depends_on:
      - django_app

  
      
volumes:
  static_vol:
  media_vol:



