# Generated by Django 4.0 on 2024-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='saw',
            field=models.SmallIntegerField(default=0),
        ),
    ]
