# Generated by Django 4.0 on 2024-01-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='count_message_saw',
            field=models.SmallIntegerField(default=0),
        ),
    ]
