# Generated by Django 4.0 on 2024-01-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_telegramuser_count_message_saw'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='firma_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
